# Generated by Django 5.0.6 on 2024-07-08 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Chamado',
                'verbose_name_plural': 'Categorias de Chamado',
                'db_table': 'chamados_categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('data_alteracao', models.DateField(auto_now_add=True, verbose_name='Data da última alteração')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='StatusChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Chamado',
                'verbose_name_plural': 'Status de Chamado',
                'db_table': 'chamados_status',
            },
        ),
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de projeto',
                'verbose_name_plural': 'Status de projeto',
                'db_table': 'projetos_status',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Subcategoria de Chamado',
                'verbose_name_plural': 'Subcategorias de Chamado',
                'db_table': 'chamados_subcategorias',
            },
        ),
        migrations.CreateModel(
            name='TipoAlteracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Alteração',
                'verbose_name_plural': 'Tipos de Alteração',
                'db_table': 'alteracoes_tipos',
            },
        ),
        migrations.CreateModel(
            name='TipoChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('retrabalho', models.BooleanField(default=False, verbose_name='Se é ou não retrabalho')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Chamado',
                'verbose_name_plural': 'Tipos de Chamado',
                'db_table': 'chamados_tipos',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'clientes_tipos',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('fone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato da filial')),
                ('matriz', models.BooleanField(default=False, verbose_name='É Matriz')),
                ('ativo', models.BooleanField(default=True, verbose_name='Filial está ou não ativa')),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('data_alteracao', models.DateField(auto_now_add=True, verbose_name='Data da última alteração')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.cliente', verbose_name='Id do tipo do cliente')),
            ],
            options={
                'verbose_name': 'Filial de cliente',
                'verbose_name_plural': 'Filiais de cliente',
                'db_table': 'clientes_filiais',
            },
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('fone', models.CharField(max_length=15, null=True, verbose_name='Telefone de contato da filial')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('solicitante', models.BooleanField(default=False, verbose_name='É Solicitante')),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('data_alteracao', models.DateField(auto_now_add=True, verbose_name='Data da última alteração')),
                ('filial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.filial', verbose_name='Filial do Contato')),
            ],
            options={
                'verbose_name': 'Contato de cliente',
                'verbose_name_plural': 'Contatos de cliente',
                'db_table': 'clientes_contatos',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Decrição completa')),
                ('descricao_resumida', models.TextField(verbose_name='Descrição resumida')),
                ('data_solicitacao', models.DateField(verbose_name='Data de cadastro')),
                ('tempo_previsao', models.DurationField(verbose_name='Tempo previsto para desenvolvimento')),
                ('data_finalizacao', models.DateField(blank=True, null=True, verbose_name='Data de finalização')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.statusprojeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Decrição completa')),
                ('descricao_resumida', models.TextField(verbose_name='Descrição resumida')),
                ('data_abertura', models.DateField(verbose_name='Data de cadastro')),
                ('data_finalizacao', models.DateField(blank=True, null=True, verbose_name='Data de finalização')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Nível de prioridade')),
                ('solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.contatocliente')),
                ('projeto_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.projeto')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.statuschamado')),
                ('subcategoria_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.subcategoriachamado')),
                ('tipo_chamado_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipochamado')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'chamados',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipocliente', verbose_name='Id do tipo do cliente'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('setor', models.CharField(max_length=30, verbose_name='Setor')),
                ('desenvolvedor', models.BooleanField(default=False, verbose_name='Usuário atua ou não como desenvolvedor')),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('data_alteracao', models.DateField(auto_now_add=True, verbose_name='Data da última alteração')),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='AlteracaoChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Decrição completa')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de registro')),
                ('tempo_trabalhado', models.DurationField(verbose_name='Tempo trabalhado')),
                ('chamado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado')),
                ('tipo_alteracao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipoalteracao')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.usuario')),
            ],
            options={
                'verbose_name': 'Alteração de Chamado',
                'verbose_name_plural': 'Alterações de Chamado',
                'db_table': 'chamados_alteracoes',
            },
        ),
    ]
